// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeKrFBUR09ccXfMSAlEH0l_eSlx4DGH-I',
    appId: '1:1053829503948:web:0c616c96ced0b436ae5b69',
    messagingSenderId: '1053829503948',
    projectId: 'aauu-5461a',
    authDomain: 'aauu-5461a.firebaseapp.com',
    storageBucket: 'aauu-5461a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCNcZpZCWuwxYVFia4XUCZi5n6ragxGUI',
    appId: '1:1053829503948:android:785421a3df5c35a4ae5b69',
    messagingSenderId: '1053829503948',
    projectId: 'aauu-5461a',
    storageBucket: 'aauu-5461a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Jk5bt2PKHB9smtchfcnQ97glKbdIhTU',
    appId: '1:1053829503948:ios:70ce808823d5605dae5b69',
    messagingSenderId: '1053829503948',
    projectId: 'aauu-5461a',
    storageBucket: 'aauu-5461a.firebasestorage.app',
    androidClientId: '1053829503948-d56p38iegd1dk570tbh7l2kcigml9iac.apps.googleusercontent.com',
    iosClientId: '1053829503948-8t6c7rcjl7sg1pd1fm6hhr6ret8vcld3.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Jk5bt2PKHB9smtchfcnQ97glKbdIhTU',
    appId: '1:1053829503948:ios:70ce808823d5605dae5b69',
    messagingSenderId: '1053829503948',
    projectId: 'aauu-5461a',
    storageBucket: 'aauu-5461a.firebasestorage.app',
    androidClientId: '1053829503948-d56p38iegd1dk570tbh7l2kcigml9iac.apps.googleusercontent.com',
    iosClientId: '1053829503948-8t6c7rcjl7sg1pd1fm6hhr6ret8vcld3.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeKrFBUR09ccXfMSAlEH0l_eSlx4DGH-I',
    appId: '1:1053829503948:web:e1174a03d3905f15ae5b69',
    messagingSenderId: '1053829503948',
    projectId: 'aauu-5461a',
    authDomain: 'aauu-5461a.firebaseapp.com',
    storageBucket: 'aauu-5461a.firebasestorage.app',
  );
}
